### ISSUE TITLE
ODBC driver is not working on Mac OS X

### ISSUE THREAD

**Issue by rom8726** [yandex/clickhouse-odbc#42]
Hi! I started clickhouse server in the Docker container and built the ODBC driver following @ztlpn  instructions (https://github.com/yandex/clickhouse-odbc/issues/35). But queries are not executed in isql:
```
MacBook-Pro-Roman:~ roman$ cat .odbc.ini
[ch]
Driver=/opt/clickhouse-odbc/build/driver/clickhouse-odbc.dylib
Description=ClickHouse driver
DATABASE=default
SERVER=172.17.0.2
PORT=8123
FRAMED=0
MacBook-Pro-Roman:~ roman$ isql -v ch
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
SQL> select 1;
[S1000]Timeout
```

**Comment by ztlpn** [comment]
Looks like this is the issue with docker networking, not with the odbc driver. To cite [docker networking guide](https://docs.docker.com/engine/userguide/networking), on macOS and Windows "docker uses network interfaces running inside a thin VM, instead of on the host machine itself". So your host system doesn't actually have direct access to the host 172.17.0.2. You can verify this with curl: `curl 'http://172.17.0.2:8123?query=select+1'` should time out just as the odbc driver did.

To mitigate the issue try to use port forwarding instead and run the clickhouse-server container with something like
```
docker run -d --ulimit nofile=262144:262144 -p 8123:8123 yandex/clickhouse-server
```
(note the `-p 8123:8123` part) and then use localhost as a server name instead of 172.17.0.2.
